/**
 * One-time (development) script: fetch Binance daily klines and write
 * `data/chartData.generated.ts` for import by `data/experiments.ts`.
 *
 * Usage (from project root):
 *   npx tsx scripts/fetchHistoricalData.ts
 *
 * Requires network access to https://api.binance.com
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export type CandleRow = {
  time: number;
  open: number;
  high: number;
  low: number;
  close: number;
};

function rawToCandles(raw: unknown): CandleRow[] {
  if (!Array.isArray(raw)) return [];
  const out: CandleRow[] = [];
  for (const row of raw) {
    if (!Array.isArray(row) || row.length < 5) continue;
    const t = Number(row[0]);
    if (!Number.isFinite(t)) continue;
    out.push({
      time: Math.floor(t / 1000),
      open: parseFloat(String(row[1])),
      high: parseFloat(String(row[2])),
      low: parseFloat(String(row[3])),
      close: parseFloat(String(row[4])),
    });
  }
  return out;
}

export function netDirection(candles: CandleRow[]): "UP" | "DOWN" {
  if (candles.length === 0) return "DOWN";
  const first = candles[0]!;
  const last = candles[candles.length - 1]!;
  return last.close >= first.open ? "UP" : "DOWN";
}

const SCENARIOS: {
  id: number;
  symbol: string;
  startTime: number;
  endTime: number;
  label: string;
}[] = [
  {
    id: 1,
    symbol: "BTCUSDT",
    startTime: Date.UTC(2022, 10, 1),
    endTime: Date.UTC(2023, 1, 10),
    label: "BTC post-FTX stabilization (daily)",
  },
  {
    id: 2,
    symbol: "ETHUSDT",
    startTime: Date.UTC(2023, 0, 1),
    endTime: Date.UTC(2023, 3, 20),
    label: "ETH Q1 2023 (daily)",
  },
  {
    id: 3,
    symbol: "SOLUSDT",
    startTime: Date.UTC(2022, 10, 1),
    endTime: Date.UTC(2023, 1, 15),
    label: "SOL late 2022–early 2023 (daily)",
  },
  {
    id: 4,
    symbol: "BNBUSDT",
    startTime: Date.UTC(2023, 2, 1),
    endTime: Date.UTC(2023, 6, 15),
    label: "BNB spring–summer 2023 (daily)",
  },
  {
    id: 5,
    symbol: "BTCUSDT",
    startTime: Date.UTC(2023, 9, 1),
    endTime: Date.UTC(2024, 1, 10),
    label: "BTC Q4 2023–Q1 2024 (daily)",
  },
  {
    id: 6,
    symbol: "ETHUSDT",
    startTime: Date.UTC(2024, 2, 1),
    endTime: Date.UTC(2024, 6, 1),
    label: "ETH Q2–Q3 2024 (daily)",
  },
  {
    id: 7,
    symbol: "SOLUSDT",
    startTime: Date.UTC(2024, 0, 1),
    endTime: Date.UTC(2024, 4, 10),
    label: "SOL H1 2024 rally window (daily)",
  },
  {
    id: 8,
    symbol: "BNBUSDT",
    startTime: Date.UTC(2022, 5, 1),
    endTime: Date.UTC(2022, 9, 1),
    label: "BNB mid-2022 stress (daily)",
  },
  {
    id: 9,
    symbol: "ETHUSDT",
    startTime: Date.UTC(2022, 8, 1),
    endTime: Date.UTC(2023, 0, 25),
    label: "ETH merge aftermath (daily)",
  },
  {
    id: 10,
    symbol: "BTCUSDT",
    startTime: Date.UTC(2022, 4, 1),
    endTime: Date.UTC(2022, 8, 1),
    label: "BTC mid-2022 drawdown (daily)",
  },
];

async function fetchKlines(
  symbol: string,
  startTime: number,
  endTime: number
): Promise<CandleRow[]> {
  const q = new URLSearchParams({
    symbol,
    interval: "1d",
    startTime: String(startTime),
    endTime: String(endTime),
  });
  const url = `https://api.binance.com/api/v3/uiKlines?${q.toString()}`;
  const res = await fetch(url);
  if (!res.ok) {
    const t = await res.text();
    throw new Error(`Binance ${res.status}: ${t.slice(0, 200)}`);
  }
  const raw: unknown = await res.json();
  return rawToCandles(raw);
}

function serializeCandles(candles: CandleRow[]): string {
  const rows = candles.map(
    (c) =>
      `      { time: ${c.time}, open: ${c.open}, high: ${c.high}, low: ${c.low}, close: ${c.close} }`
  );
  return `[\n${rows.join(",\n")}\n    ]`;
}

async function main(): Promise<void> {
  const byRound: Record<number, CandleRow[]> = {};
  const summary: { id: number; dir: "UP" | "DOWN"; n: number }[] = [];

  for (const s of SCENARIOS) {
    const candles = await fetchKlines(s.symbol, s.startTime, s.endTime);
    if (candles.length < 60) {
      console.warn(`Round ${s.id}: only ${candles.length} candles`);
    }
    byRound[s.id] = candles;
    const dir = netDirection(candles);
    summary.push({ id: s.id, dir, n: candles.length });
    await new Promise((r) => setTimeout(r, 150));
  }

  const entries = SCENARIOS.map((s) => {
    const c = byRound[s.id]!;
    return `    ${s.id}: ${serializeCandles(c)}`;
  }).join(",\n");

  const file = `/**
 * AUTO-GENERATED by scripts/fetchHistoricalData.ts — do not edit by hand.
 * Real Binance 1d OHLCV; re-run script to refresh.
 */
import type { Candle } from "@/lib/types";

export const CHART_BY_ROUND: Record<number, Candle[]> = {
${entries}
};
`;

  const outPath = path.join(process.cwd(), "data", "chartData.generated.ts");
  await mkdir(path.dirname(outPath), { recursive: true });
  await writeFile(outPath, file, "utf8");

  console.log(`Wrote ${outPath}`);
  console.log("\nNet direction (first open → last close):");
  for (const x of summary) {
    console.log(`  Round ${x.id}: ${x.dir} (${x.n} candles)`);
  }
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
